### ISSUE TITLE
Transformers

### ISSUE THREAD

**Issue by CrushCandy** [LansanaCamara/Medium#3]
Why are these even existing? Its rather confusing

**Comment by LansanaCamara** [comment]
They're there for the front end. For example, I may not want to handle some logic in the Models because then it would apply to everything after it's taken from the DB, but I can manipulate the data right before it's sent out as a response to make lesser of a need for client-side logic.

Turn numbers to int type, turn booleans to boolean type, exclude some data and even rename properties.

Also I may call a function on a property in the transformer -- a function I don't want called on it in the model or controller because there I would need the raw value since it may be used elsewhere, but right before the request is sent I want to do something to it.

**Comment by CrushCandy** [comment]
You might want to take some time to look into 'presenters' :dash:

**Comment by LansanaCamara** [comment]
Looks pretty promising.. seems to be the same idea done cleaner. Will look into that later, thanks.

**Comment by CrushCandy** [comment]
I can implement the use of repositories and presenters but a lot needs to be moved around, would be a lot cleaner end result.

End result would be a method like :   view()->with('user', $user->retrieveByID(5)->presenter());

This would mean, you can read and user it like you do currently, but in an easier fashion

**Comment by LansanaCamara** [comment]
You on laravel irc?

**Comment by CrushCandy** [comment]
will do now
